"""final for now

Revision ID: 28825fc20009
Revises: 
Create Date: 2026-04-05 23:35:36.423795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28825fc20009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_created_at'))
        batch_op.drop_index(batch_op.f('ix_order_ord_id'))
        batch_op.drop_index(batch_op.f('ix_order_user_id'))

    op.drop_table('order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_pay_id'))
        batch_op.drop_index(batch_op.f('ix_payment_user_id'))

    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pay_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_pay_id'), ['pay_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_payment_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_created_at'), ['created_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ord_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_ord_id'), ['ord_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
