"""new column added- reciptent_username to Order

Revision ID: facebd1ad8a1
Revises: 28825fc20009
Create Date: 2026-04-08 20:27:37.910353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facebd1ad8a1'
down_revision = '28825fc20009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reciptent_username', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('reciptent_username')

    # ### end Alembic commands ###
